language: node_js
sudo: required
services:
- docker
before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- npm run pull || true
script:
- npm run build
- npm test
deploy:
  provider: script
  script: docker push vixlet/nginx:alpine
  skip_cleanup: true
  on:
    branch: master
    repo: Vixlet/docker-nginx