#!/bin/sh
echo "Substituting environment variables..." \
  && ls /etc/nginx/nginx.conf.template | /root/envsubst \
  && ls /etc/nginx/conf.d/*.conf.template | /root/envsubst \
  && echo "Starting Nginx..." \
  && if [ "${#}" -lt 1 ]; then exec nginx -g "daemon off;"; else exec "${@}"; fi