#!/bin/sh
if [[ "$PRODUCTION_MODE" == 'off' ]]; then
  DEVELOPMENT_MODE='on'
else
  DEVELOPMENT_MODE='off'
fi
echo "Substituting environment variables..." \
  && ls /etc/nginx/nginx.conf.template | /root/envsubst \
  && ls /etc/nginx/conf.d/*.conf.template | /root/envsubst \
  && ls /etc/nginx/includes.d/*.conf.template | /root/envsubst \
  && ls /etc/nginx/sites-available/*.conf.template | /root/envsubst \
  && ls /etc/nginx/sites-enabled/*.conf.template | /root/envsubst \
  && echo "Starting Nginx..." \
  && if [ "${#}" -lt 1 ]; then exec nginx -g "daemon off;"; else exec "${@}"; fi